version: '2'
services:

  haproxy:
    build: ./haproxy
    container_name: haproxy
    environment:
     - WEBSERVER1=nginx1
     - WEBSERVER2=nginx2
    ports:
     - "8881:80"
    depends_on:
     - nginx1
     - nginx2
    links:
     - nginx1
     - nginx2
    

  nginx1:
    build: ./nginx
    container_name: nginx1
    expose:
     - "80"
    ports:
     - "8081:80"
     
  nginx2:
    build: ./nginx
    container_name: nginx2
    expose:
     - "80"
    ports:
     - "8082:80"
